name: "DVM config action"
description: "Action to extract the DVM config file."
author: "Tatsuya Okayama"
branding:
  icon: "bookmark"
  color: "blue"
inputs:
  project-dir:
    description: "The path to the directory where the project exists."
    required: false
    default: "."
outputs:
  dart-sdk-version:
    description: "The version of Dart SDK specified in the DVM config file."
    value: ${{ steps.extract.outputs.dart-sdk-version }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: extract
      run: main.sh
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
        PROJECT_DIR: ${{ inputs.project-dir }}
