name: extract
description: "CLI app to extract DVM configuration files."
version: 1.0.0

executables:
  extract: app

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
